apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: pra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: flask-pra:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: pra-data
